theme: jekyll-theme-minimal
title: Joe Kodweis
description: Embedded Software Developer, Linux enthusiast, technology geek, BS Computer Engineering
Round robin of social media: https://www.linkedin.com/in/kodweis
And why not... kodweis.com. Let's see if the search engines pick this up
